import { Star, Compass, Cpu } from "lucide-react";
const skills = [
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Node.js",
  "HTML",
  "CSS",
  "Tailwind CSS",
  "MongoDB",
  "PostgreSQL",
  "GraphQL",
  "REST API",
  "Git",
  "Docker",
  "AWS",
  "Firebase",
  "Redux",
  "Express",
  "Jest",
  "React Native",
  "Framer Motion",
  "Figma",
  "UI/UX Design",
];

const projects = [
  {
    title: "Budget Beam",
    description: "Personal Finance Tracker",
    tech: ["Next.js", "PostgreSQL,", "Drizzle ORM", "Clerk", "Tailwind CSS"],
    image: "/budgetBeam.png",
    color: "primary",
    icon: <Star className="h-5 w-5" />,
    glowClass: "primary-glow",
    github: "https://github.com/ShlokRamteke/Budget-Beam",
    live: "https://budget-beam-buddy.vercel.app/",
  },
  {
    title: "FormInsight",
    description: "A Form Data Analysis Tool",
    tech: [
      "RAG,",
      "Gemini,",
      "LLM",
      "Material UI",
      "Reactjs",
      "Nodejs",
      "Express.js,",
    ],
    image: "formInsight.png",
    color: "secondary",
    icon: <Compass className="h-5 w-5" />,
    glowClass: "secondary-glow",
    github: "https://github.com/ShlokRamteke/rag_forms",
    live: "https://rag-forms.vercel.app/",
  },
  {
    title: "The Inklings",
    description: "A Full-Stack Blog Application.",
    tech: ["Reactjs", "Node.js", "Express.js", "MySQL", "JWT"],
    image: "inkling.png",
    color: "accent",
    icon: <Cpu className="h-5 w-5" />,
    glowClass: "accent-glow",
    github: "https://github.com/ShlokRamteke/blog_sql",
    live: "https://inklings-tech.netlify.app/",
  },
  {
    title: "Game Maneger",
    description: "A Game Library Manager",
    tech: ["Reactjs", "Node.js", "Express.js", "MongoDB"],
    image: "game-library.png",
    color: "primary",
    icon: <Cpu className="h-5 w-5" />,
    glowClass: "primary-glow",
    github: "https://github.com/ShlokRamteke/game-manger",
    live: "https://mygamemanager.netlify.app/",
  },
];
export { skills, projects };
